//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIplusEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_System_User
    {
        public int ID { get; set; }
        public string SYSTEM_USER { get; set; }
        public string CURRENT_USER { get; set; }
    }
}
